---
title: "R Notebook"
output: html_notebook
---



```{r}
library(readr)
library(dplyr)
library(ggplot2)
```

2 DIGIT DECADE
```{r}
setwd("~/Dropbox/thesis/5_APST/julia_compute_distance/src") 


df <- read_csv("../output/2digit_decade/spca_distance_7.csv")[,-1]

split <- split(df, with(df, interaction(decade)), drop = TRUE)

split$"1990"

split$"1990" <- split$"1990"[,-2:-4]

df <- inner_join(split$"1990", split$"1980", by = c("occupation"), suffix=c("_1990","_1980"))

df$distance_change <- df$mean_distance_1990 - df$mean_distance_1980
lf <- read_csv("/Users/jsusser/Dropbox/thesis/4_CPS/clean_HPV/output/Codes/1digit_occupations.csv")[,-1]


lf$`occupation`[lf$`codes` == 2] <- 'Sales/Admin'
lf$`occupation`[lf$`codes` == 1] <- 'Tech/Manage/Professional'
lf$`occupation`[lf$`codes` == 5] <- 'Production/Operators'
lf$`occupation`[lf$`codes` == 6] <- 'Production/Operators'
df <- df %>%
  left_join(lf, by=c('1digit occ'='codes'))


ggplot(df, aes(reorder(occupation.x, `2digit occ`), y = distance_change, color=`occupation.y`)) + geom_point() +   
  theme_light()+
  theme(legend.title=element_blank()) +
  
   scale_color_manual(values = c("black", "black","darkgreen", "#CA0020", "blue")) +
  theme(axis.text.x=element_text(angle=65,size=10))+
labs(title="Occupation, sorted by code v Change in distance SPCA (1980s-1990s)", x="Occupation, sorted by code", y="Change in distance (1980s-1990s)")
ggsave("../output/spca_change_distance_2digit_occ_pc.png", width = 10, height=7)
  
```

2 DIGIT DECADE W JUST SERVICE AND PRODUCTION
```{r}
df <- read_csv("../output/2digit_decade/pca_distance_7.csv")[,-1] 

split <- split(df, with(df, interaction(decade)), drop = TRUE)

split$"1990" <- split$"1990"[,-2:-4]

df <- inner_join(split$"1990", split$"1980", by = c("occupation"), suffix=c("_1990","_1980"))

df$distance_change <- df$mean_distance_1990 - df$mean_distance_1980
lf <- read_csv("/Users/jsusser/Dropbox/thesis/4_CPS/clean_HPV/output/Codes/1digit_occupations.csv")[,-1]


lf$`occupation`[lf$`codes` == 2] <- 'Sales/Admin'
lf$`occupation`[lf$`codes` == 1] <- 'Tech/Manage/Professional'
lf$`occupation`[lf$`codes` == 5] <- 'Production/Operators'
lf$`occupation`[lf$`codes` == 6] <- 'Production/Operators'

df <- df %>%
  left_join(lf, by=c('1digit occ'='codes'))
df <- subset(df, `occupation.y`== 'Production/Operators' | `occupation.y`== 'Service')

ggplot(df, aes(reorder(occupation.x, `2digit occ`), y = distance_change, color=`occupation.y`)) + geom_point() +  
    theme_light()+
  theme(legend.title=element_blank()) +

   scale_color_manual(values = c("black", "#CA0020")) +
  theme(axis.text.x=element_text(angle=65,size=10))+
labs(title="Occupation, sorted by code v Change in distance (1980s-1990s)", x="Occupation, sorted by code", y="Change in distance (1980s-1990s)")
ggsave("../output/pca_change_distance_2digit-service-production.png", width = 10, height=7)
```


```{r}
df <- read_csv("../output/2digit_5yr/pca_distance_3.csv")[,-1]
lf <- read_csv("/Users/jsusser/Dropbox/thesis/4_CPS/clean_HPV/output/Codes/1digit_occupations.csv")[,-1]


lf$`occupation`[lf$`codes` == 2] <- 'Sales/Admin'
lf$`occupation`[lf$`codes` == 1] <- 'Tech/Manage/Professional'
lf$`occupation`[lf$`codes` == 5] <- 'Production/Operators'
lf$`occupation`[lf$`codes` == 6] <- 'Production/Operators'

df <- df %>%
  left_join(lf, by=c('1digit occ'='codes'))
df <- subset(df, `occupation.y`== 'Production/Operators' | `occupation.y`== 'Service')


ggplot(df, aes(x =`decade`, y = mean_distance, color=`occupation.x`)) + geom_line() +   
  theme_light()+
  theme(legend.title=element_blank()) +
  
  # scale_color_manual(values = c("black", "darkgreen", "#CA0020", "blue")) +
  theme(axis.text.x=element_text(angle=65,size=10))+
labs(title="5yr v Mean Distance PCA_3 (1980s-1990s)", x="5 Year", y="Mean distance")
```





