---
title: "R Notebook"
output: html_notebook
---
import libraries:
```{r}
library(dplR)
library(readr)
library(dplyr)
library(ggplot2)
library(kernlab)
library(sparsepca)
```


```{r}
#145
"technology_vydec" %in% names(lf)
```




PCA everything:
```{r}
df <- read_csv("../input/occ_skill.csv")
years <- c(1950,1960,1970,1980,1990,2001)
t <-1940
#goes through it by 10 years
for (yeary in years){
  #selecting 10 years
  lf <- df %>% 
    filter(year >= t & year <= yeary -1)
#orders by first occ then year
  lf <- lf[
    with(lf, order(occ1990dd, year)),
  ]
  #saves lf for future use
  h <- lf
  
  #takes out year and occ1990
  lf <- lf[,-1:-2]
  #takes out 2 digit and 1 digit occ
  lf <- lf[,-207:-208]
  lf <- lf[,-186]
  lf.pca <- prcomp(lf, scale = TRUE, center = TRUE)
  print(t)
  t  <- yeary
}



for (num in c(3,4,7)){
  k <- lf.pca$x[,1:num]
  
  filename <- paste("../output/pca/pca",toString(t),"/pca_normal_",toString(t), "s_",toString(num), ".csv", sep="", collapse=NULL)
  #writes pca into data frame but bc it is a matrix
  write.csv(k,filename)
  #reads data and can edit it because it is now a frame
  d <- read_csv(filename)
  
  
  
  d <- d %>% 
    select(-X1)
  #uses original frame to attach the occ and year
  h <- h %>%
    select(occ1990dd, year)
  d <- cbind(h,d)
  
  write.csv(d,filename)
}
```



PCA by decade:
```{r}
df <- read_csv("../input/occ_skill.csv")

df <- df[
  with(df, order(occ1990dd, year)),
]
h <- df
df <- df[,-1:-2]
df <- df[,-207:-208]
df.pca <- prcomp(df, scale = TRUE, center = TRUE)
for (num in c(3,4,7)){
  k <- df.pca$x[,1:num]
  write.csv(k,paste("../output/pca/pca_everything/pca normal ", toString(num), ".csv", sep="", collapse=NULL))
  d <- read_csv(paste("../output/pca/pca_everything/pca normal ", toString(num), ".csv", sep="", collapse=NULL))
  d <- d %>% 
    select(-X1)
  h <- h %>%
    select(occ1990dd, year)
  d <- cbind(h,d)
  write.csv(d,paste("../output/pca/pca_everything/pca normal ", toString(num), ".csv", sep="", collapse =NULL))
}

```


KPCA everything:
WHEN YOU WANT TO RUN THIS, CHANGE INCLUDE TO TRUE!
```{r, eval=False}
df <- read_csv("../input/occ_skill.csv")
df <- df[
  with(df, order(occ1990dd, year)),
]
h <- df

df <- df[,-1:-2]
df <- df[,-207:-208]
kpc <- kpca(~.,data=df,kernel="rbfdot",
            kpar=list(sigma=0.2),features=7)
for (num in c(3,4,7)){
k <- pcv(kpc)[,1:num]
write.csv(k,paste("../output/kpca/kpca_everything/kernel pca everything ",toString(num), ".csv", sep="", collapse=NULL))
d <- read_csv(paste("../output/kpca/kpca_everything/kernel pca everything ",toString(num), ".csv", sep="", collapse=NULL))
if (num>=3){
d <- d %>% rename(PC1 = V1, PC2 = V2, PC3 = V3)
}
if (num>=4){
d <- d %>% rename(PC4 = V4)
}
if (num>=7){
d <- d %>% rename(PC5 = V5, PC6 = V6, PC7 = V7)
}

d <- d %>% 
  select(-X1)
h <- h %>%
  select(occ1990dd, year)
d <- cbind(h,d)
write.csv(d,paste("../output/kpca/kpca_everything/kernel pca everything ",toString(num), ".csv", sep="", collapse=NULL))

}
```



KCPA by decade:
WHEN YOU WANT TO RUN THIS, CHANGE INCLUDE TO TRUE!
```{r, eval=False}
df <- read_csv("../input/occ_skill.csv")
data(df)

#df <- df %>% distinct(occ1990dd, .keep_all = TRUE)

years <- c(1950,1960,1970,1980,1990,2001)
t <-1940
for (yeary in years){
  lf <- df %>% 
    filter(year >= t & year <= yeary -1)
  print(lf)
 
lf <- lf[
  with(lf, order(occ1990dd, year)),
]
h <- lf

lf <- lf[,-1:-2]
lf <- lf[,-207:-208]

kpc <- kpca(~.,data=lf,kernel="rbfdot",
            kpar=list(sigma=0.2),features=7)


for (num in c(3,4,7)){
k <- pcv(kpc)[,1:num]

write.csv(k,paste("../output/kpca/kpca",toString(t),"/kernel pca ",toString(t), "s_",toString(num), ".csv", sep="", collapse=NULL))
d <- read_csv(paste("../output/kpca/kpca",toString(t),"/kernel pca ",toString(t), "s_",toString(num), ".csv", sep="", collapse=NULL))
if (num>=3){
d <- d %>% rename(PC1 = V1, PC2 = V2, PC3 = V3)
}
if (num>=4){
d <- d %>% rename(PC4 = V4)
}
if (num>=7){
d <- d %>% rename(PC5 = V5, PC6 = V6, PC7 = V7)
}

d <- d %>% 
  select(-X1)
h <- h %>%
  select(occ1990dd, year)
d <- cbind(h,d)
write.csv(d,paste("../output/kpca/kpca",toString(t),"/kernel pca ",toString(t), "s_",toString(num), ".csv", sep="", collapse=NULL))
}
t <- yeary
}
```

SPCA everything:
```{r}
df <- read_csv("../input/occ_skill.csv")
df <- df[
  with(df, order(occ1990dd, year)),
]
h <- df

df <- df[,-1:-2]
df <- df[,-207:-208]
df <- data.frame(t(df))
names(df) <- h$occ1990dd
df

myPr <- spca(df, k=7, alpha=1e-4, beta=1e-4, center=TRUE, scale=FALSE, max_iter=1000, tol=1e-5, verbose=TRUE)

for (num in c(3,4,7)){
k <- myPr$loadings[,1:num]

write.csv(k,paste("../output/spca/spca_everything/sparse pca everything ",toString(num), ".csv", sep="", collapse=NULL))
d <- read_csv(paste("../output/spca/spca_everything/sparse pca everything ",toString(num), ".csv", sep="", collapse=NULL))
if (num>=3){
d <- d %>% rename(PC1 = V1, PC2 = V2, PC3 = V3)
}
if (num>=4){
d <- d %>% rename(PC4 = V4)
}
if (num>=7){
d <- d %>% rename(PC5 = V5, PC6 = V6, PC7 = V7)
}

d <- d %>% 
  select(-X1)
h <- h %>%
  select(occ1990dd, year)
d <- cbind(h,d)


write.csv(d,paste("../output/spca/spca_everything/sparse pca everything ",toString(num), ".csv", sep="", collapse=NULL))

}
```


SPCA by decade:
```{r}
df <- read_csv("../input/occ_skill.csv")
data(df)
years <- c(1950,1960,1970,1980,1990,2001)
t <-1940
for (yeary in years){
  lf <- df %>% 
    filter(year >= t & year <= yeary -1)

  
lf <- lf[
  with(lf, order(occ1990dd, year)),
]
h <- lf
lf <- lf[-1:-2]
lf <- lf[,-207:-208]
lf <- data.frame(t(lf))
names(lf) <- h$occ1990dd

myPr <- spca(lf, k=7, alpha=1e-4, beta=1e-4, center=TRUE, scale=FALSE, max_iter=1000, tol=1e-5, verbose=TRUE)
for (num in c(3,4,7)){
k <- myPr$loadings[,1:num]

write.csv(k,paste("../output/spca/spca",toString(t),"/sparse pca ",toString(t), "s_",toString(num), ".csv", sep="", collapse=NULL))
d <- read_csv(paste("../output/spca/spca",toString(t),"/sparse pca ",toString(t), "s_",toString(num), ".csv", sep="", collapse=NULL))
if (num>=3){
d <- d %>% rename(PC1 = V1, PC2 = V2, PC3 = V3)
}
if (num>=4){
d <- d %>% rename(PC4 = V4)
}
if (num>=7){
d <- d %>% rename(PC5 = V5, PC6 = V6, PC7 = V7)
}

d <- d %>% 
  select(-X1)
h <- h %>%
  select(occ1990dd, year)
d <- cbind(h,d)

write.csv(d,paste("../output/spca/spca",toString(t),"/sparse pca ",toString(t), "s_",toString(num), ".csv", sep="", collapse=NULL))
}
t  <- yeary 
}
```

