---
title: "R Notebook"
output: html_notebook
---



```{r}

library(readr)
library(dplyr)
library(ggplot2)
library(kernlab)
```


```{r}
df <- read_csv("../input/occ_skill.csv")
df <- df[
  with(df, order(occ1990dd, year)),
]
h <- df

df <- df[,-1:-2]
df <- df[,-207:-208]
df
```


```{r}
kpc <- kpca(~.,data=df,kernel="rbfdot",
            kpar=list(sigma=0.2),features=7)
```


```{r}
for (num in c(3,4,7)){
k <- pcv(kpc)[,1:num]
write.csv(k,paste("../output/kpca/kpca_everything/kernel pca everything ",toString(num), ".csv", sep="", collapse=NULL))
d <- read_csv(paste("../output/kpca/kpca_everything/kernel pca everything ",toString(num), ".csv", sep="", collapse=NULL))
if (num>=3){
d <- d %>% rename(PC1 = V1, PC2 = V2, PC3 = V3)
}
if (num>=4){
d <- d %>% rename(PC4 = V4)
}
if (num>=7){
d <- d %>% rename(PC5 = V5, PC6 = V6, PC7 = V7)
}

hh <- c()
for (x in seq(1,length(h$occ1990dd)))
{
  occ <- h$occ1990dd[x]
  yr <- h$year[x]
  hh <- append(hh,paste(toString(occ),"_",toString(yr), sep="", collapse=NULL))
}

d <- d %>% 
  select(-X1)

row.names(d)<- hh
write.csv(d,paste("../output/kpca/kpca_everything/kernel pca everything ",toString(num), ".csv", sep="", collapse=NULL))

}
```



