---
title: "R Notebook"
#output: html_notebook
---


```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(haven)
library(ggpubr)
setwd("~/Dropbox/thesis/5_APST/keyword/src") 
kf <- read_dta("../input/data_by_occ_code_year.dta")

kf$`two digit` =cut(kf$occ_code,
                 breaks = c(0,22, 37,200, 235,283,389,408,427,444,447,455,472,498,549,599,617,699,799,890), labels=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19))

a <- kf %>%
  filter(year == 1983) %>%
    group_by(`two digit`) %>%
      summarize(words_1983 = sum(words*ct2))
b <- kf %>%
  filter(year == 2000) %>%
    group_by(`two digit`) %>%
      summarize(words_2000 = sum(words*ct2))

kf <- a %>%
  full_join(b, by=c('two digit'))
kf$dif_words <- kf$words_2000 - kf$words_1983

```


```{r}
setwd("~/Dropbox/thesis/5_APST/julia_compute_distance/src") 


df <- read_csv("../output/2digit_decade/pca_distance_3.csv")[,-1]

split <- split(df, with(df, interaction(decade)), drop = TRUE)



split$"1990" <- split$"1990"[,-2:-4]

df <- inner_join(split$"1990", split$"1980", by = c("occupation"), suffix=c("_1990","_1980"))

df$log_distance_change <- df$mean_distance_1990 - df$mean_distance_1980
lf <- read_csv("/Users/jsusser/Dropbox/thesis/4_CPS/clean_HPV/output/Codes/1digit_occupations.csv")[,-1]

lf <- lf %>%
  filter(codes != 4)
lf$`occupation`[lf$`codes` == 2] <- 'Sales/Admin'
lf$`occupation`[lf$`codes` == 1] <- 'Tech/Manage/Professional'
lf$`occupation`[lf$`codes` == 5] <- 'Production/Operators'
lf$`occupation`[lf$`codes` == 6] <- 'Production/Operators'
df <- df %>%
  inner_join(lf, by=c('1digit occ'='codes'))
kf$`2occ` <- as.numeric(row.names(kf))
df <- df %>%
  inner_join(kf, by=c('2digit occ'='2occ'))
df
```


```{r}

ggplot(df, aes(reorder(occupation.x, dif_words), y=log_distance_change, color=`occupation.y`)) + geom_point(size=5)+  
  theme_light() +
  theme(legend.title=element_blank())+
  
  
  scale_color_manual(values = c("blue2", "black", "#CA0020","darkgreen")) + 
  theme(axis.text.x=element_text(angle=65,size=10))+
  
  
  labs(title="Change in Distance (pca3), sorted by change in sum of all words*ads in the sector", x="Occupation, sorted by change in sum of all words*ads in the sector (asc)", y="Change in distance from 1980-1990(higher-more dissimilarity)")


ggsave("/Users/jsusser/Desktop/r.png", width = 7, height=6)
```





